import 'dotenv/config';
import { fbAuth } from './src/config/firebase-admin.js';

async function createAuthUser() {
  const email = 'superadmin@feeti.cg';
  const password = 'superadmin123';
  const displayName = 'Super Admin';
  // Use the ID generated by Prisma if we wanted them to match perfectly,
  // but Firebase can generate its own UID, or we can fetch the user from Prisma
  // and use that ID. Let's fetch from Prisma to keep UIDs aligned!
  
  import('./src/config/database.js').then(async ({ connectToDatabase, prisma }) => {
    await connectToDatabase();
    const user = await prisma.user.findUnique({ where: { email } });
    
    if (!user) {
      console.error("Utilisateur non trouvé dans PostgreSQL !");
      process.exit(1);
    }

    try {
      // Try to get user to see if it already exists
      await fbAuth.getUserByEmail(email);
      console.log(`L'utilisateur ${email} existe déjà dans Firebase Auth.`);
      
      // Update password just in case
      await fbAuth.updateUser(user.id, { password });
      console.log(`Mot de passe mis à jour dans Firebase Auth.`);
    } catch (error: any) {
      if (error.code === 'auth/user-not-found') {
        console.log(`Création de l'utilisateur ${email} dans Firebase Auth avec l'ID ${user.id}...`);
        await fbAuth.createUser({
          uid: user.id,
          email,
          password,
          displayName,
        });
        console.log("✅ Utilisateur créé dans Firebase Auth !");
      } else {
        console.error("Erreur inattendue:", error);
      }
    }
    
    await prisma.$disconnect();
    process.exit(0);
  });
}

createAuthUser();
