import { PrismaClient } from '../../src/generated/prisma/client.js';

const leisureItemsData = [
  // ═══════════════════════════════════════════════════════════════
  //  HOTELS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Samba Lodge',
    description: 'Établissement de prestige au bord du fleuve Congo. Cadre exceptionnel alliant saveurs marines et ambiance tropicale. Chef renommé, piscine à débordement et service VIP.',
    categorySlug: 'hotels',
    location: 'Kingdom Tower, Brazzaville',
    address: 'Avenue du Fleuve, Brazzaville',
    phone: '+242 06 123 45 67',
    website: 'www.sambalodge.cg',
    priceRange: '45 000 - 85 000 FCFA',
    openingHours: '24h/24',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop',
    rating: 4.9,
    reviewCount: 347,
    features: JSON.stringify(['Piscine', 'Restaurant gastronomique', 'Bar lounge', 'Vue fleuve', 'WiFi', 'Parking']),
    tags: JSON.stringify(['Bar', 'Hôtel', 'Piscine', 'Gastronomie']),
    status: 'published',
    countryCode: 'CG',
    isFeatured: true,
    latitude: -4.2634,
    longitude: 15.2429,
  },
  {
    name: 'Exaunelle Resort',
    description: 'Villa de rêve nichée dans un écrin de verdure tropicale. Intimiste et ultra-luxueux, parfait pour une escapade romantique avec soins spa et piscine privée.',
    categorySlug: 'hotels',
    location: 'Route de Kinkala, Brazzaville',
    address: 'Route panoramique de Kinkala',
    phone: '+242 06 234 56 78',
    priceRange: '55 000 - 95 000 FCFA',
    openingHours: '24h/24',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop',
    rating: 4.8,
    reviewCount: 156,
    features: JSON.stringify(['Spa premium', 'Piscine privée', 'Jardin tropical', 'Suites royales']),
    tags: JSON.stringify(['Spa', 'Hôtel', 'Piscine', 'Romantique']),
    status: 'published',
    countryCode: 'CG',
    isFeatured: true,
    latitude: -4.3200,
    longitude: 15.1800,
  },
  {
    name: 'Hôtel Fleuve Congo',
    description: 'Au cœur de Kinshasa, un établissement 4 étoiles alliant confort premium et fonctionnalité. Idéal pour les voyageurs d\'affaires avec centre de conférences et restaurant gastronomique.',
    categorySlug: 'hotels',
    location: 'Gombe, Kinshasa',
    address: 'Avenue Colonel Ebeya, Gombe, Kinshasa',
    phone: '+243 81 234 56 78',
    priceRange: '75 000 - 150 000 FCFA',
    openingHours: '24h/24',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&h=600&fit=crop',
    rating: 4.6,
    reviewCount: 312,
    features: JSON.stringify(['Piscine', 'Spa', 'Centre de conférences', 'Restaurant', 'WiFi haut débit']),
    tags: JSON.stringify(['Business', 'Luxe', 'Piscine', 'Conférences']),
    status: 'published',
    countryCode: 'CD',
    isFeatured: false,
    latitude: -4.3012,
    longitude: 15.3234,
  },
  {
    name: 'Radisson Blu Libreville',
    description: 'Hôtel 5 étoiles face à l\'océan Atlantique à Libreville. Chambres panoramiques, piscine en rooftop et restaurant de fruits de mer avec vue imprenable sur l\'estuaire.',
    categorySlug: 'hotels',
    location: 'Bord de mer, Libreville',
    address: 'Boulevard du Bord de Mer, Libreville',
    phone: '+241 01 234 567',
    priceRange: '80 000 - 200 000 FCFA',
    openingHours: '24h/24',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop',
    rating: 4.7,
    reviewCount: 289,
    features: JSON.stringify(['Piscine rooftop', 'Vue océan', 'Restaurant fruits de mer', 'Bar panoramique', 'Spa']),
    tags: JSON.stringify(['Luxe', 'Vue mer', 'Gabon', 'Romantique']),
    status: 'published',
    countryCode: 'GA',
    isFeatured: true,
    latitude: 0.3902,
    longitude: 9.4542,
  },

  // ═══════════════════════════════════════════════════════════════
  //  RESTAURANTS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'La Terrasse Gourmande',
    description: 'Restaurant gastronomique avec terrasse panoramique sur le fleuve Congo. Cuisine fusion afro-française avec des produits locaux de saison. Menu dégustation disponible.',
    categorySlug: 'restaurants',
    location: 'Centre-ville, Brazzaville',
    address: 'Avenue des Nations-Unies, Brazzaville',
    phone: '+242 05 678 90 12',
    priceRange: '15 000 - 45 000 FCFA',
    openingHours: '12h00 - 23h00',
    image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop',
    rating: 4.7,
    reviewCount: 203,
    features: JSON.stringify(['Terrasse vue fleuve', 'Menu dégustation', 'Cave à vins', 'Cuisine fusion', 'Réservation recommandée']),
    tags: JSON.stringify(['Gastronomie', 'Terrasse', 'Vue fleuve', 'Fusion']),
    status: 'published',
    countryCode: 'CG',
    isFeatured: true,
    latitude: -4.2661,
    longitude: 15.2832,
  },
  {
    name: 'Restaurant Chez Mama Jeanne',
    description: 'Le meilleur de la cuisine kinoise authentique. Poulet moambé, fumbwa, pondu et bien plus dans une ambiance chaleureuse et familiale. Buffet à volonté le dimanche.',
    categorySlug: 'restaurants',
    location: 'Gombe, Kinshasa',
    address: 'Avenue Bokasa, Gombe, Kinshasa',
    phone: '+243 99 876 54 32',
    priceRange: '8 000 - 25 000 FCFA',
    openingHours: '11h00 - 22h00',
    image: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=600&fit=crop',
    rating: 4.7,
    reviewCount: 165,
    features: JSON.stringify(['Cuisine locale', 'Buffet dominical', 'Ambiance familiale', 'Plats végétariens']),
    tags: JSON.stringify(['Cuisine locale', 'Buffet', 'Famille', 'RDC']),
    status: 'published',
    countryCode: 'CD',
    isFeatured: false,
    latitude: -4.3158,
    longitude: 15.3217,
  },
  {
    name: 'Le Maquis du Plateau',
    description: 'Cuisine ivoirienne authentique au cœur d\'Abidjan. Alloco, kedjenou, attiéké et jus de gingembre frais. Brunch ivoirien premium le weekend.',
    categorySlug: 'restaurants',
    location: 'Plateau, Abidjan',
    address: 'Avenue Botreau Roussel, Plateau, Abidjan',
    phone: '+225 07 123 45 67',
    priceRange: '5 000 - 20 000 FCFA',
    openingHours: '07h00 - 22h00',
    image: 'https://images.unsplash.com/photo-1559964114-f8b3d8c8b41c?w=800&h=600&fit=crop',
    rating: 4.8,
    reviewCount: 221,
    features: JSON.stringify(['Cuisine locale CI', 'Brunch weekend', 'Jus naturels', 'Terrasse']),
    tags: JSON.stringify(['Côte d\'Ivoire', 'Traditionnel', 'Brunch', 'Abidjan']),
    status: 'published',
    countryCode: 'CI',
    isFeatured: false,
    latitude: 5.3543,
    longitude: -4.0018,
  },

  // ═══════════════════════════════════════════════════════════════
  //  SPORT & BIEN-ETRE
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Zen Wellness Center',
    description: 'Centre de bien-être premium offrant massages relaxants, hammam, sauna et soins beauté. Espace entièrement dédié à votre détente avec des thérapeutes certifiés.',
    categorySlug: 'sports',
    location: 'Pointe-Noire, Congo',
    address: 'Avenue Général de Gaulle, Pointe-Noire',
    phone: '+242 05 999 88 77',
    priceRange: '15 000 - 45 000 FCFA',
    openingHours: '08h00 - 21h00',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&h=600&fit=crop',
    rating: 4.6,
    reviewCount: 89,
    features: JSON.stringify(['Massage relaxant', 'Hammam', 'Sauna', 'Soins beauté', 'Piscine de détente']),
    tags: JSON.stringify(['Spa', 'Relaxation', 'Bien-être', 'Massage']),
    status: 'published',
    countryCode: 'CG',
    isFeatured: false,
    latitude: -4.7762,
    longitude: 11.8634,
  },
  {
    name: 'FitLife Club',
    description: 'Salle de fitness moderne équipée des dernières machines cardio et musculation. Cours collectifs quotidiens : yoga, zumba, HIIT. Coachs certifiés disponibles.',
    categorySlug: 'sports',
    location: 'Cocody, Abidjan',
    address: 'Boulevard de la Corniche, Cocody, Abidjan',
    phone: '+225 01 234 56 78',
    priceRange: '10 000 - 30 000 FCFA / mois',
    openingHours: '06h00 - 22h00',
    image: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=600&fit=crop',
    rating: 4.5,
    reviewCount: 134,
    features: JSON.stringify(['Cardio', 'Musculation', 'Yoga', 'Zumba', 'Coaching personnalisé', 'Vestiaires']),
    tags: JSON.stringify(['Fitness', 'Sport', 'Abidjan', 'Coaching']),
    status: 'published',
    countryCode: 'CI',
    isFeatured: false,
    latitude: 5.3559,
    longitude: -3.9838,
  },

  // ═══════════════════════════════════════════════════════════════
  //  LOISIRS
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Gaming Lounge Kinshasa',
    description: 'L\'espace gaming le plus branché de Kinshasa. Tournois hebdomadaires, consoles dernière génération, zone VR et snack-bar. Idéal pour groupes d\'amis et anniversaires.',
    categorySlug: 'loisirs',
    location: 'Ngaliema, Kinshasa',
    address: 'Avenue des Aviateurs, Ngaliema, Kinshasa',
    phone: '+243 97 112 33 44',
    priceRange: '2 000 - 8 000 FCFA / heure',
    openingHours: '10h00 - 01h00',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=600&fit=crop',
    rating: 4.4,
    reviewCount: 78,
    features: JSON.stringify(['Consoles PS5/Xbox', 'Réalité virtuelle', 'Tournois', 'Snack-bar', 'WiFi fibre']),
    tags: JSON.stringify(['Gaming', 'Jeux vidéo', 'Jeunes', 'VR']),
    status: 'published',
    countryCode: 'CD',
    isFeatured: false,
    latitude: -4.3166,
    longitude: 15.2852,
  },
  {
    name: 'Bowling Galaxie',
    description: 'Le seul bowling moderne de Libreville avec 12 pistes. Ambiance lumineuse, bar-restaurant intégré et salle de jeux pour toute la famille. Location de chaussures incluse.',
    categorySlug: 'loisirs',
    location: 'Libreville',
    address: 'Centre Commercial Mbolo, Libreville',
    phone: '+241 01 456 789',
    priceRange: '5 000 - 12 000 FCFA / partie',
    openingHours: '14h00 - 00h00',
    image: 'https://images.unsplash.com/photo-1529494792912-8ae2f7e8e1e5?w=800&h=600&fit=crop',
    rating: 4.3,
    reviewCount: 112,
    features: JSON.stringify(['12 pistes', 'Bar-restaurant', 'Salle de jeux', 'Billard', 'Anniversaires']),
    tags: JSON.stringify(['Bowling', 'Famille', 'Gabon', 'Jeux']),
    status: 'published',
    countryCode: 'GA',
    isFeatured: false,
    latitude: 0.3905,
    longitude: 9.4604,
  },

  // ═══════════════════════════════════════════════════════════════
  //  EVASION
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Congo Safari Tours',
    description: 'Spécialiste des excursions nature au Congo. Safari au Parc de Loango, observation des gorilles et des éléphants de mer. Guides certifiés et hébergement en lodge éco-responsable.',
    categorySlug: 'envolee',
    location: 'Parc National Loango, Congo',
    address: 'Point de départ : Pointe-Noire',
    phone: '+242 06 777 88 99',
    priceRange: '84 000 - 250 000 FCFA',
    openingHours: 'Sur réservation',
    image: 'https://images.unsplash.com/photo-1547036967-23d11aacaee0?w=800&h=600&fit=crop',
    rating: 4.9,
    reviewCount: 234,
    features: JSON.stringify(['Safari guidé', 'Observation faune', 'Lodge éco', 'Transport inclus', 'Repas inclus']),
    tags: JSON.stringify(['Safari', 'Nature', 'Aventure', 'Loango']),
    status: 'published',
    countryCode: 'CG',
    isFeatured: true,
    latitude: -4.7762,
    longitude: 11.8634,
  },
  {
    name: 'Gabon Dive Center',
    description: 'Centre de plongée certifié PADI à Cap Lopez. Découverte des récifs coralliens gabonais, rencontre avec raies manta et tortues marines. Cours débutants et plongées experts.',
    categorySlug: 'envolee',
    location: 'Cap Lopez, Port-Gentil',
    address: 'Cap Lopez, Port-Gentil, Gabon',
    phone: '+241 07 890 123',
    priceRange: '39 000 - 85 000 FCFA',
    openingHours: '07h00 - 17h00',
    image: 'https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=800&h=600&fit=crop',
    rating: 4.9,
    reviewCount: 67,
    features: JSON.stringify(['Plongée certifiée PADI', 'Cours débutants', 'Location équipement', 'Guide sous-marin', 'Photos sous-marines']),
    tags: JSON.stringify(['Plongée', 'Océan', 'Gabon', 'Aventure']),
    status: 'published',
    countryCode: 'GA',
    isFeatured: true,
    latitude: -0.7193,
    longitude: 8.7815,
  },

  // ═══════════════════════════════════════════════════════════════
  //  BAR & NUIT
  // ═══════════════════════════════════════════════════════════════
  {
    name: 'Rooftop Sky Lounge',
    description: 'Bar rooftop au sommet du building le plus haut de Brazzaville. Vue panoramique à 360° sur la ville et le fleuve. Cocktails premium, DJ sets les vendredis et samedis.',
    categorySlug: 'bar-night',
    location: 'Centre-ville, Brazzaville',
    address: 'Tour CCIA, Brazzaville',
    phone: '+242 06 555 44 33',
    priceRange: '5 000 - 20 000 FCFA',
    openingHours: '18h00 - 03h00',
    image: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&h=600&fit=crop',
    rating: 4.8,
    reviewCount: 189,
    features: JSON.stringify(['Vue panoramique', 'Cocktails premium', 'DJ sets', 'Happy hour', 'Réservation VIP']),
    tags: JSON.stringify(['Rooftop', 'Bar', 'Vue', 'DJ', 'VIP']),
    status: 'published',
    countryCode: 'CG',
    isFeatured: true,
    latitude: -4.2661,
    longitude: 15.2832,
  },
  {
    name: 'Club Afrobeats Abidjan',
    description: 'La référence de la nuit abidjanaise. Soirées afrobeats, coupé-décalé et R&B avec les meilleurs DJs locaux et internationaux. VIP tables avec service bouteille.',
    categorySlug: 'bar-night',
    location: 'Marcory, Abidjan',
    address: 'Zone 4, Marcory, Abidjan',
    phone: '+225 07 654 32 10',
    priceRange: '5 000 - 50 000 FCFA',
    openingHours: '22h00 - 06h00',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&h=600&fit=crop',
    rating: 4.6,
    reviewCount: 445,
    features: JSON.stringify(['Afrobeats', 'Tables VIP', 'DJ internationaux', 'Service bouteille', 'Dress code']),
    tags: JSON.stringify(['Club', 'Nuit', 'Afrobeats', 'VIP', 'Abidjan']),
    status: 'published',
    countryCode: 'CI',
    isFeatured: false,
    latitude: 5.3096,
    longitude: -3.9788,
  },
];

export async function seedLeisureItems(prisma: PrismaClient, adminId: string) {
  await prisma.leisureItem.deleteMany({ where: { createdById: adminId } });

  let count = 0;
  for (const item of leisureItemsData) {
    await prisma.leisureItem.create({ data: { ...item, createdById: adminId } });
    count++;
  }

  const byCat: Record<string, number> = {};
  leisureItemsData.forEach(i => { byCat[i.categorySlug] = (byCat[i.categorySlug] ?? 0) + 1; });
  console.log(`✅ ${count} loisirs créés :`);
  for (const [slug, n] of Object.entries(byCat)) {
    console.log(`   • ${slug} — ${n} loisirs`);
  }
}
